Version 1.1.0 Arbitrary preferences support tinted icons and text appearance PreferenceScreens support tinted icons and text appearance Tinted icons and text appearance accessible from XpPreferenceHelpers class Fixed NoSuchMethodError introduced in last release